In [14]:
import os
import pandas as pd
from sqlalchemy import create_engine
from dotenv import load_dotenv

load_dotenv()
DATABASE_URL = os.getenv("DATABASE_URL")

In [15]:

engine = create_engine(DATABASE_URL)

ArgumentError: Could not parse SQLAlchemy URL from given URL string

In [10]:
query = """
SELECT *
FROM users
LIMIT 10;
"""

df = pd.read_sql(query, engine)

print(df)

    user_id signup_date         country           plan          persona  \
0  U0000000  2022-05-16  United Kingdom        monthly          student
1  U0000001  2021-01-03          Brazil           free  career_switcher
2  U0000002  2021-04-23           India  financial_aid        upskiller
3  U0000003  2023-01-23         Ukraine           free  career_switcher
4  U0000004  2021-10-24          Mexico        monthly  career_switcher
5  U0000005  2021-05-10          Brazil        monthly        upskiller
6  U0000006  2022-09-01           Other           free        upskiller
7  U0000007  2021-10-11         Germany        monthly  career_switcher
8  U0000008  2021-06-07   United States        monthly          student
9  U0000009  2021-01-07   United States        monthly  career_switcher

  age_band device_primary
0    35-44        desktop
1    35-44        desktop
2    35-44        desktop
3    18-24         mobile
4    18-24        desktop
5    18-24        desktop
6      45+         mobile
7    25-34         mobile
8    25-34         mobile
9    35-44        desktop

In [4]:
query = """
SELECT
    plan,
    COUNT(*) AS users
FROM users
GROUP BY plan
ORDER BY users DESC;
"""

pd.read_sql(query, engine)

            plan  users
0           free  18480
1        monthly  13626
2         annual   5589
3  financial_aid   2305

In [11]:
query = """
SELECT
    ROUND(
        100.0 * AVG(is_certified),
        2
    ) AS certification_rate
FROM enrollments;
"""

pd.read_sql(query, engine)

   certification_rate
0                4.81